### ISSUE TITLE
[Tauschbörse] Auswertungs-Tool

### ISSUE THREAD

**Issue by Birne94** [Pokefans/Pokefans#27]
Ein moderatives Tool zum auswerten folgender Daten (jeweils eines Monats, nach Möglichkeit auch Quartalsweise, jährliche Auswertung):
- Häufigst getauschtes Pokémon/Item
- User mit den meisten Transaktionen und Anzahl der Gesamt-Transaktionen.

**Comment by hackathi** [comment]
Done.
