### ISSUE TITLE
Filteroptionen erweitern

### ISSUE THREAD

**Issue by Vegeta1005** [Pokefans/Pokefans#33]
Filteroptionen in der TB sollen erweitern werten (Preis aufsteigend/absteigend, Vertrauenswürdigkeit aufsteigend/absteigend, genaue DV/EV-Kombinationen, (Zucht-)attacken, Typ, ID und OT, Fähigkeiten, Bänder).

**Comment by hackathi** [comment]
Das ist denke ich durch die (erweiterte) Suchfunktion gut abgedeckt.
