### ISSUE TITLE
Anpassbares Schulden-Maximum

### ISSUE THREAD

**Issue by Vegeta1005** [Pokefans/Pokefans#39]
Dynamische Anpassung des Schuldenmaximus für neue User, ansteigbar (auf ein Limit) bei längerer Aktivität. (Nur nötig falls die heutigen TP bestehen bleiben)

**Comment by hackathi** [comment]
TP bleiben.

**Comment by hackathi** [comment]
Dreieinhalb Jahre später bleiben die TP nicht :D
