### ISSUE TITLE
Detailangaben bei TB-Angeboten

### ISSUE THREAD

**Issue by Vegeta1005** [Pokefans/Pokefans#42]
Detailliertere Angaben zu den angebotenen Pokémon nötig (Bänder, definierte DV/EV, Spezialform (z. B. bei Rotom, Pumpjin oder Arceus), Fähigkeiten, OT und ID angebar als Pflichtfeld).

**Comment by hackathi** [comment]
"Detailliertere Angaben" sind zu vage, um als konkrete Implementationsvorschrift gelten zu können. Detaillierter als bisher sind die Angaben...
