### ISSUE TITLE
Tauschpunkte vergebbar 

### ISSUE THREAD

**Issue by Vegeta1005** [Pokefans/Pokefans#47]
Nur für die Moderation: Die Funktion einbauen durch ein Passwort eine bestimmte Menge an TP zu erhalten, z. B. als Gewinn bei bestimmten Aktionen. Ein Passwort sollte nur von TB-Mods angelegt werden können, ebenfalls gut: Eine Passwort-Mindestlänge.

**Comment by hackathi** [comment]
Keine TP, deshalb nicht notwendig.
