### ISSUE TITLE
Statusänderung

### ISSUE THREAD

**Issue by Vegeta1005** [Pokefans/Pokefans#50]
Auswahlmöglichkeit "Betrugsfall" sowie "Gelöscht durch die Tauschaufsicht" beim Rückbuchen (unter "Status"). Mod-exklusiv.
Komplette Auswahlmöglichkeiten für Status wie bei "Tausch rückbuchen" auch bei "Einzelne Angebote eines Nutzers löschen"

**Comment by hackathi** [comment]
Tauschangebote können durch die Moderation gelöscht werden (z.B. bei Falschangaben, Cheats, ...).
