### ISSUE TITLE
Aktivitäts-Diagramme

### ISSUE THREAD

**Issue by Vegeta1005** [Pokefans/Pokefans#51]
Digramme der aktivsten Nutzer der TB -> Auflistung der häufigsten Tauschpartner und häufigst angebotenen "Produkte" um gezielte TP-Manipulation zu verhindern, eventuell mit/beim Mitarbeiterdiagramm integrieren.

**Comment by hackathi** [comment]
Gibt keine TP mehr, daher irrelevant.
