### ISSUE TITLE
Ausgebesserte Falschangaben/ Löschungen von Angeboten eines users

### ISSUE THREAD

**Issue by Vegeta1005** [Pokefans/Pokefans#54]
In der Tabelle mit den Betrugsfällen sollte in einer neuen Spalte noch aufgezählt werden, wie oft beim Benutzer schon Falschangaben korregiert/ Angebote gelöscht werden mussten.

**Comment by hackathi** [comment]
-> BVS

**Comment by hackathi** [comment]
Jeder Vorgang erzeugt jetzt einen BVS-Eintrag. Einen Counter insgesamt gibt es nicht.
