### ISSUE TITLE
Automatische löschungen von TB-Angeboten

### ISSUE THREAD

**Issue by Vegeta1005** [Pokefans/Pokefans#56]
Automatische Löschung nach Ablauf von 60 Tagen von TB-Angeboten.

**Comment by PokefansTL** [comment]
Das sollte besser von der User-Aktivität abhängen. Solange der User auf Anfragen noch reagiert ist es ja okay - nicht jedes Angebot bekommt man innerhalb von 60 Tagen los ...

**Comment by hackathi** [comment]
Ich habe jetzt eine Warnmeldung bei sehr alten Angeboten (> 180 Tage) eingeblendet. Ich denke, das sollte das auch erst mal lösen. Von einer automatischen Löschung halte ich nichts.

**Comment by hackathi** [comment]
Ahja, der Anbieter kann dann einen Knopf drücken mit dem das Angebot wieder als aktuell markiert wird, dann ist die Frist wieder von neuem da.
