### ISSUE TITLE
Warteperiode bei Tauscherfüllung

### ISSUE THREAD

**Issue by hackathi** [Pokefans/Pokefans#57]
Um das mal Festgehalten zu haben:

wenn ein Tausch auf "Erledigt" gestellt wird, werden derzeit die TP sofort übertragen. Das hat zu einigen Betrugfsällen geführt. Folgendes neue System schlage ich daher vor:

Nach der Markierung des Tauschs als "Erledigt" wird der Tausch in das Tauschprotokoll geschrieben. Ab diesem Zeitpunkt beginnt eine 48h Warteperiode. Nach Ablauf der 48h werden die TP gut geschrieben. Während dieser Zeit hat der Tauschpartner die Möglichkeit, den Tausch als Betrugsfall zu markieren. Damit verlängert sich die Frist bis zur Gutschrift der TP auf eine Woche. Der Tausch wird zusätzlich im Backend als Betrugsfall geführt und wird dann moderativ behandelt werden. Die Moderation hat hier die Möglichkeit, die Frist zu verlängern (sollte das notwendig sein) oder das Geschäft Rückabzuwickeln.

Bestätigt der Tauschpartner innerhalb der 48h-Frist den Tausch, werden die TP auch sofort gut geschrieben.

**Comment by Vegeta1005** [comment]
Kann gerne so ins neue System eingebracht werden, finde ich wirklich gut.

**Comment by PokefansTL** [comment]
Halte ich ebenfalls für eine sinnvolle Idee ...

**Comment by hackathi** [comment]
Gibt ja keine TP mehr, aber bevor der Tausch in die Statistiken eingeht gibt es trotzdem 48h Warteperiode.
