### ISSUE TITLE
Warnmeldung für Tab schließen beim Artikel bearbeiten

### ISSUE THREAD

**Issue by Jonkins** [Pokefans/Pokefans#63]
Wenn ich Artikel schreibe, kommt es vor, dass ich ausversehen den Tab schließe, beispielsweise durch Strg+Leertaste statt Strg+C oder Ähnliches.
Eine Meldung "Wollen sie den Tab wirklich schließen?", wenn es ungespeicherte Informationen gibt, wäre sehr hilfreich.

**Comment by hackathi** [comment]
https://github.com/Pokefans/Pokefans/blob/master/Pokefans/Scripts/ace/content-edit.js#L61

Gibt's schon.
