### ISSUE TITLE
Mitarbeiter-Datenbank und SQL-Abfrage in Artikeln

### ISSUE THREAD

**Issue by Jonkins** [Pokefans/Pokefans#64]
Ein größerer Wunsch, von dem ich von Luke bereits weiß, dass er nicht umsetzbar / zu kompliziert wäre.
Es wäre mir eine große Hilfe, wenn Mitarbeiter Datenbanken anlegen könnten und per SQL-Abfrage daraus Tabellen und Ähnliches für Artikel generieren könnten. Dadurch könnten manche Artikel allgemein einfacher erstellt werden und die Redundanz würde verringert werden. Erst gestern durfte ich über 150 Artikel updaten, weil Niantic einige Werte in Pokémon GO verändert hat. Mit einem solchen System wären es nur ein paar Klicks gewesen.
Wohl einer der größten Wünsche, aber würde auch einiges vereinfachen und oft genutzt werden, gerade wenn der Dex auch darauf zugreifen könnte.

**Comment by hackathi** [comment]
SQL wird es sicher nicht geben - über eine REST-API für bestehende Datenbanken können wir aber reden. Aber auch da wären Updates zwangsläufig Rate-Limited, damit ein wild gewordenes Skript nicht innerhalb von Sekunden ganz Pokefans zerlegen kann.

**Comment by hackathi** [comment]
Und, um es hier nochmal stehen zu haben: Wer Abfragen braucht, soll einen Pull-Request schicken. Dafür sind wir ja Open Source, oder so.

**Comment by PokefansTL** [comment]
Dafür gäbe es möglicherweise eine bessere Lösung, die mit weniger Aufwand realisieren lässt und keine Performance-Nachteile mit sich bringt. Werden wir zuerst intern besprechen ...
