### ISSUE TITLE
Verschiebemoderation FA-Galerie

### ISSUE THREAD

**Issue by wandi0909** [Pokefans/Pokefans#68]
Das Verschieben von Werken in eine andere Kategorie in der neuen Galerie ist noch nicht funktionsfähig.. wie es scheint.

**Comment by hackathi** [comment]
Problem ist auf Windows gefixt, für Linux wartet es auf diesen Pullrequest: https://github.com/mono/mono/pull/3559

**Comment by hackathi** [comment]
Ist seit mono 4.8 gefixt.
